import { MANUAL_LINKS_FIELD } from './frontmatter.js';

function demoId(slug) {
  return `demo-constellation-${slug}`;
}

function makeEntry({
  slug,
  type,
  title,
  tags,
  status,
  notes,
  links = [],
  url,
  channel,
  duration,
  guest,
  episode,
  highlight,
}) {
  const id = demoId(slug);
  return {
    id,
    type,
    title,
    tags,
    status,
    notes,
    links: links.map(demoId),
    [MANUAL_LINKS_FIELD]: true,
    ...(url ? { url } : {}),
    ...(channel ? { channel } : {}),
    ...(duration ? { duration } : {}),
    ...(guest ? { guest } : {}),
    ...(episode ? { episode } : {}),
    ...(highlight ? { highlight } : {}),
  };
}

export function getConstellationDemoEntries() {
  return [
    makeEntry({
      slug: 'atlas-index',
      type: 'note',
      title: 'Atlas Index',
      tags: ['demo-constellation', 'systems', 'mapping'],
      status: 'active',
      notes: 'Hub note for the demo vault. Start with [[Signal Garden]], [[Deep Work Broadcast]], and [[Field Notes 2026-04-24]].',
      links: ['signal-garden', 'deep-work-broadcast', 'field-notes'],
    }),
    makeEntry({
      slug: 'signal-garden',
      type: 'note',
      title: 'Signal Garden',
      tags: ['demo-constellation', 'synthesis', 'patterns'],
      status: 'active',
      notes: 'Cluster root for article and link material. Mirrors ideas from [[Attention Cartography]], [[Tooling Without Bloat]], and [[Bridge Thread]].',
      links: ['attention-cartography', 'tooling-without-bloat', 'bridge-thread'],
    }),
    makeEntry({
      slug: 'attention-cartography',
      type: 'article',
      title: 'Attention Cartography',
      tags: ['demo-constellation', 'reading', 'attention'],
      status: 'reading',
      notes: 'Long-form read connected to [[Signal Garden]] and [[Bridge Thread]].',
      links: ['signal-garden', 'bridge-thread'],
      url: 'https://example.com/attention-cartography',
    }),
    makeEntry({
      slug: 'tooling-without-bloat',
      type: 'link',
      title: 'Tooling Without Bloat',
      tags: ['demo-constellation', 'tooling', 'workflow'],
      status: 'active',
      notes: 'Reference link that keeps the systems cluster grounded. Related to [[Signal Garden]] and [[Workshop Ledger]].',
      links: ['signal-garden', 'workshop-ledger'],
      url: 'https://example.com/tooling-without-bloat',
    }),
    makeEntry({
      slug: 'bridge-thread',
      type: 'note',
      title: 'Bridge Thread',
      tags: ['demo-constellation', 'bridges', 'mapping'],
      status: 'active',
      notes: 'Cross-cluster bridge between [[Signal Garden]], [[Night Shift Dispatch]], and [[Orbit Review]].',
      links: ['signal-garden', 'night-shift-dispatch', 'orbit-review'],
    }),
    makeEntry({
      slug: 'deep-work-broadcast',
      type: 'podcast',
      title: 'Deep Work Broadcast',
      tags: ['demo-constellation', 'audio', 'focus'],
      status: 'listening',
      notes: 'Anchor episode for the audio cluster. Pairs with [[Night Shift Dispatch]], [[Ambient Systems Vol. 2]], and [[Bridge Thread]].',
      links: ['night-shift-dispatch', 'ambient-systems-vol-2', 'bridge-thread'],
      url: 'https://example.com/deep-work-broadcast',
      guest: 'Mara Quinn',
      episode: '118',
      highlight: 'Build quiet systems before you build more surface area.',
    }),
    makeEntry({
      slug: 'night-shift-dispatch',
      type: 'podcast',
      title: 'Night Shift Dispatch',
      tags: ['demo-constellation', 'audio', 'ops'],
      status: 'saved',
      notes: 'Ops-heavy conversation linked to [[Deep Work Broadcast]] and [[Orbit Review]].',
      links: ['deep-work-broadcast', 'orbit-review'],
      url: 'https://example.com/night-shift-dispatch',
      guest: 'Elio Marsh',
      episode: '07',
      highlight: 'Reliability is attention management in disguise.',
    }),
    makeEntry({
      slug: 'ambient-systems-vol-2',
      type: 'video',
      title: 'Ambient Systems Vol. 2',
      tags: ['demo-constellation', 'video', 'systems'],
      status: 'watched',
      notes: 'Video companion to [[Deep Work Broadcast]] and [[Workshop Ledger]].',
      links: ['deep-work-broadcast', 'workshop-ledger'],
      url: 'https://example.com/ambient-systems-vol-2',
      channel: 'Pattern Signal',
      duration: '18m',
    }),
    makeEntry({
      slug: 'field-notes',
      type: 'journal',
      title: 'Field Notes 2026-04-24',
      tags: ['demo-constellation', 'journal', 'ops'],
      status: 'complete',
      notes: 'Daily snapshot that ties [[Atlas Index]], [[Workshop Ledger]], and [[Orbit Review]] together.',
      links: ['atlas-index', 'workshop-ledger', 'orbit-review'],
    }),
    makeEntry({
      slug: 'workshop-ledger',
      type: 'note',
      title: 'Workshop Ledger',
      tags: ['demo-constellation', 'building', 'inventory'],
      status: 'active',
      notes: 'Maker cluster root. Connects [[Field Notes 2026-04-24]], [[Ambient Systems Vol. 2]], [[Prototype Loop]], and [[Signal Garden]].',
      links: ['field-notes', 'ambient-systems-vol-2', 'prototype-loop', 'signal-garden'],
    }),
    makeEntry({
      slug: 'prototype-loop',
      type: 'video',
      title: 'Prototype Loop',
      tags: ['demo-constellation', 'video', 'workflow'],
      status: 'watching',
      notes: 'Fast demo linked into [[Workshop Ledger]] and [[Orbit Review]].',
      links: ['workshop-ledger', 'orbit-review'],
      url: 'https://example.com/prototype-loop',
      channel: 'Studio Relay',
      duration: '11m',
    }),
    makeEntry({
      slug: 'orbit-review',
      type: 'article',
      title: 'Orbit Review',
      tags: ['demo-constellation', 'review', 'strategy'],
      status: 'read later',
      notes: 'Review article that acts as the second bridge. References [[Prototype Loop]], [[Night Shift Dispatch]], and [[Bridge Thread]].',
      links: ['prototype-loop', 'night-shift-dispatch', 'bridge-thread'],
      url: 'https://example.com/orbit-review',
    }),
  ];
}
