export const workstationEntries = [
  {
    id: 'p-1',
    type: 'project',
    title: 'JotFolio Phase 2',
    tags: ['product'],
    status: 'active',
    space: 'work',
    due: '2026-06-01',
    progress: '68%',
    date: '2026-05-12T09:00:00.000Z',
    _path: 'projects/JotFolio Phase 2.md',
    links: [],
  },
  {
    id: 'n-1',
    type: 'note',
    title: 'Local-first Roadmap',
    tags: ['product', 'planning'],
    status: 'active',
    project: 'p-1',
    space: 'work',
    date: '2026-05-13T10:00:00.000Z',
    entry_date: '2026-05-13',
    _path: 'notes/Local-first Roadmap.md',
    notes: 'Plan the vault shell around capture, search, tasks, and recovery.',
    links: ['p-1'],
  },
  {
    id: 't-1',
    type: 'task',
    title: 'Review route rendering',
    tags: ['planning'],
    status: 'open',
    project: 'p-1',
    source_entry: 'n-1',
    space: 'work',
    due: '2026-05-14',
    priority: 'high',
    completed: false,
    date: '2026-05-14T08:00:00.000Z',
    _path: 'tasks/Review route rendering.md',
    links: ['n-1'],
  },
  {
    id: 't-2',
    type: 'task',
    title: 'Completed shell audit',
    tags: ['planning'],
    status: 'done',
    project: 'p-1',
    space: 'work',
    due: '2026-05-14',
    priority: 'low',
    completed: true,
    date: '2026-05-13T08:00:00.000Z',
    _path: 'tasks/Completed shell audit.md',
    links: ['n-1'],
  },
  {
    id: 'raw-1',
    type: 'raw',
    title: 'Inbox capture from meeting',
    tags: ['capture'],
    status: 'captured',
    date: '2026-05-14T09:00:00.000Z',
    _path: 'inbox/Inbox capture from meeting.md',
    links: [],
  },
  {
    id: 'w-1',
    type: 'wiki',
    title: 'Wiki Memory: Local-first Principles',
    tags: ['product'],
    status: 'reviewed',
    review_after: '2026-05-14',
    date: '2026-05-11T09:00:00.000Z',
    notes: 'Durable memory should cite source entries and stay local.',
    _path: 'wiki/Local-first Principles.md',
    links: ['n-1'],
  },
];
